# Generated by Django 5.2 on 2025-04-24 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('devices', '0005_alter_device_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('correct_shoulder_position', models.BooleanField()),
                ('correct_neck_position', models.BooleanField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posture_data',
                                             to='devices.device')),
            ],
        ),
    ]
