# Generated by Django 5.2 on 2025-04-24 15:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('devices', '0005_alter_device_api_key'),
        ('posture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('overall_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0),
                                                                  django.core.validators.MaxValueValidator(100)])),
                ('device',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posture_readings',
                                   to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PostureComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('neck', 'Neck Position'), ('torso', 'Torso Position'),
                                                             ('shoulders', 'Shoulders Position')], max_length=10)),
                ('is_correct', models.BooleanField()),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0),
                                                          django.core.validators.MaxValueValidator(100)])),
                ('correction', models.CharField(max_length=255)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components',
                                              to='posture.posturereading')),
            ],
        ),
        migrations.DeleteModel(
            name='PostureData',
        ),
        migrations.AddIndex(
            model_name='posturereading',
            index=models.Index(fields=['device', 'timestamp'], name='posture_pos_device__b4612e_idx'),
        ),
        migrations.AddIndex(
            model_name='posturecomponent',
            index=models.Index(fields=['reading', 'component_type'], name='posture_pos_reading_c1e796_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='posturecomponent',
            unique_together={('reading', 'component_type')},
        ),
    ]
