# Generated by Django 5.2 on 2025-04-24 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture', '0002_posturereading_posturecomponent_delete_posturedata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posturereading',
            name='overall_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
