# Generated by Django 5.2 on 2025-04-28 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posture", "0003_alter_posturereading_overall_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posturecomponent",
            name="correction",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="posturecomponent",
            name="score",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="posturereading",
            name="overall_score",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
