# Generated by Django 5.2 on 2025-05-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posture", "0004_alter_posturecomponent_correction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posturecomponent",
            name="correction",
        ),
        migrations.RemoveField(
            model_name="posturecomponent",
            name="is_correct",
        ),
        migrations.AddField(
            model_name="posturecomponent",
            name="raw_data",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
