# Generated by Django 5.2 on 2025-05-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posture", "0005_remove_posturecomponent_correction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posturecomponent",
            name="raw_data",
        ),
    ]
