# Generated by Django 5.2 on 2025-04-22 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Device', max_length=100)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sensitivity', models.PositiveIntegerField(default=50.0)),
                ('vibration_intensity', models.PositiveIntegerField(default=50.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
