# Generated by Django 5.2 on 2025-04-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('devices', '0003_alter_device_is_active_alter_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='api_key',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
