# Generated by Django 5.2 on 2025-04-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('devices', '0004_device_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='api_key',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
