# Generated by Django 5.2 on 2025-04-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0006_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
