# Generated by Django 5.2 on 2025-05-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0007_device_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="audio_intensity",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
