# Generated by Django 5.2 on 2025-05-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0008_device_audio_intensity"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="is_idle",
            field=models.BooleanField(default=False),
        ),
    ]
