name: Code Check

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main", "develop" ]

jobs:
  code-check:
    runs-on: docker
    container:
      image: catthehacker/ubuntu:act-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          make install-dev

      - name: Run linting
        run: make lint

      - name: Run tests
        run: make test

      - name: Check formatting
        run: |
          # We just check formatting, we don't apply it in CI
          black --line-length 120 --check --diff .
          isort --check --diff .